# Generated by Django 4.1.7 on 2023-03-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.TextField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.TextField(max_length=25)),
                ('adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_number', models.TextField(max_length=50)),
                ('order_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('initial_quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Selling.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Selling.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('firstname', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel_number', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('ordered', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Selling.ordered')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Selling.product')),
            ],
        ),
    ]
